import { useEffect, useState } from 'react'
import { useLocation, Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2, ShieldAlert, ShieldCheck } from 'lucide-react'
import CapabilityGraph from '../components/CapabilityGraph'
import { api } from '../services/api'
import type { SimulationResult } from '../types'
export default function Compare() {
  const location = useLocation()
  const [comparison, setComparison] = useState<SimulationResult | null>(() => (location.state as { simulation?: SimulationResult } | null)?.simulation || JSON.parse(sessionStorage.getItem('scopelens-comparison') || 'null'))
  const [error, setError] = useState('')
  useEffect(() => { if (comparison) return; api.scenarios().then(async all => { const support = all.find(s => s.id === 'support_agent'); if (support) setComparison(await api.simulate(support, 'email.send_external')) }).catch(() => setError('Could not load demo comparison. Start the backend and reload.')) }, [comparison])
  if (!comparison) return <section className="page"><h1>Loading comparison…</h1>{error && <p className="error">{error}</p>}</section>
  const { before, after, difference } = comparison
  const coreAvailable = after.capabilities.includes('DATA_READ_SENSITIVE') && after.capabilities.includes('DATA_WRITE')
  const externalAllowed = (result: typeof before) => result.capabilities.includes('EXTERNAL_SEND')
  return <section className="page compare-page"><div className="compare-intro"><div className="eyebrow">BEFORE & AFTER</div><h1>One permission. <em>Less access. Less risk.</em></h1><p>Removing <code>{difference.removed_permission}</code> changes what {before.agent.name} can reach. Every number and graph below comes from a fresh deterministic analysis.</p></div><div className="compare-grid"><article className="compare-panel before"><div className="compare-label"><ShieldAlert size={20}/> BEFORE SCOPELENS</div><div className="compare-score"><strong>{before.score}</strong><span className="severity-pill">{before.severity}</span></div><div className="compare-meta"><div><span>Risks</span><strong>{before.risks.length}</strong></div><div><span>External email</span><strong>{externalAllowed(before) ? 'Allowed' : 'Blocked'}</strong></div></div><div className="compare-graph"><CapabilityGraph graph={before.graph} compact/></div><div className="compare-permissions"><span>PERMISSIONS</span><div>{before.normalized_permissions.map(p => <span className={p.permission === difference.removed_permission ? 'highlight-permission' : ''} key={p.permission}>{p.permission}</span>)}</div></div></article><article className="compare-panel after"><div className="compare-label"><ShieldCheck size={20}/> AFTER SCOPELENS</div><div className="compare-score"><strong>{after.score}</strong><span className="severity-pill">{after.severity}</span></div><div className="compare-meta"><div><span>Risks</span><strong>{after.risks.length}</strong></div><div><span>External email</span><strong>{externalAllowed(after) ? 'Allowed' : 'Blocked'}</strong></div></div><div className="compare-graph"><CapabilityGraph graph={after.graph} compact/></div><div className="compare-permissions"><span>PERMISSIONS</span><div>{after.normalized_permissions.map(p => <span key={p.permission}>{p.permission}</span>)}</div></div></article></div><div className="compare-outcome"><div className="outcome-icon"><CheckCircle2 size={24}/></div><div><strong>{coreAvailable ? 'Core task still available.' : 'Review core task availability.'}</strong><p>{coreAvailable ? 'The agent can still read customer data and create support tickets.' : 'The removed permission may affect the agent’s stated task.'} {difference.removed_risks.length} risks removed.</p></div><Link to="/new" className="button secondary">Check your AI <ArrowRight size={16}/></Link></div></section>
}
