import { Activity, ArrowRight, FileLock2, GitBranch, ShieldCheck, ShieldOff, ScanSearch, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'

export default function Landing() {
  return <>
    <section className="hero page dashboard-hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot"/> AI AGENT SECURITY · BEFORE AND DURING EXECUTION</div><h1>See the blast radius. <em>Stop the wrong move.</em></h1><p className="lead">ScopeLens analyzes what an agent <strong>could do</strong> before deployment, then watches what it <strong>tries to do</strong> at runtime.</p><div className="hero-actions"><Link to="/live" className="button primary">Open Live Agent Lab <ArrowRight size={18}/></Link><Link to="/new" className="button secondary">Analyze permissions</Link></div><div className="hero-note"><ShieldCheck size={17}/> Deterministic guard · Synthetic sandbox · Works without a model</div></div><div className="dashboard-preview"><div className="preview-top"><span><span className="small-dot green"/> SCOPELENS LIVE</span><span>CODE ASSISTANT</span></div><div className="preview-flow"><div><span className="preview-icon neutral"><GitBranch size={21}/></span><strong>Project</strong><small>Allowed</small></div><div className="preview-line"/><div><span className="preview-icon agent"><Sparkles size={21}/></span><strong>Agent</strong><small>Reading issue.txt</small></div><div className="preview-line danger"/><div><span className="preview-icon danger"><FileLock2 size={21}/></span><strong>Demo secret</strong><small>Blocked</small></div></div><div className="preview-alert"><ShieldOff size={18}/><div><strong>Critical scope deviation blocked</strong><span>Untrusted issue → secret outside workspace</span></div><b>BLOCK</b></div><div className="preview-bottom"><span>1 untrusted source</span><span>1 critical request</span><span>Core task continues</span></div></div></section>
    <section className="page product-split"><div className="product-card"><div className="product-icon"><ScanSearch size={25}/></div><div className="eyebrow">SCOPELENS ANALYZE · PRE-DEPLOYMENT</div><h2>What could this agent do?</h2><p>Combine permissions across tools and providers into one capability graph. Find dangerous chains, then remove one permission to see the blast radius shrink.</p><div className="product-tags"><span>Permissions</span><span>Resources</span><span>Risk paths</span></div><Link to="/new" className="text-button">Start an analysis <ArrowRight size={17}/></Link></div><div className="product-card live"><div className="product-icon"><Activity size={25}/></div><div className="eyebrow">SCOPELENS LIVE · RUNTIME</div><h2>What is this agent doing?</h2><p>Watch agent movement through files and tools. The runtime guard allows legitimate work, asks for human approval, and blocks dangerous scope deviations.</p><div className="product-tags"><span>Live actions</span><span>Blocked actions</span><span>Approvals</span></div><Link to="/live" className="text-button">Explore the Live Lab <ArrowRight size={17}/></Link></div></section>
    <section className="page feature-section"><div className="section-heading"><div className="eyebrow">THE DEMO STORY</div><h2>One issue. One hidden instruction. One clear boundary.</h2><p>A coding agent reads a synthetic project issue containing an untrusted instruction. In unprotected sandbox mode, it can reach a fake secret. With ScopeLens enabled, the same request is blocked while code review continues.</p></div><div className="demo-steps"><div><span>01</span><strong>Read the issue</strong><small>Legitimate project task</small></div><div><span>02</span><strong>Spot the deviation</strong><small>Untrusted content requests a fake secret</small></div><div><span>03</span><strong>Block in code</strong><small>Guard stops out-of-scope access</small></div></div><Link to="/live/compare" className="button secondary">See before vs after <ArrowRight size={17}/></Link></section>
  </>
}
