import { ArrowRight, FileLock2, FolderOpen, ShieldCheck, ShieldOff, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'

export default function Landing() {
  return <>
    <section className="hero page dashboard-hero"><div className="hero-copy"><div className="eyebrow"><span className="pulse-dot"/> SCOPELENS · AI ACCESS & PROTECTION</div><h1>Your AI has a job. <em>Keep it there.</em></h1><p className="lead">See what your AI can access. Watch what it tries to do. Stop actions you never asked for.</p><div className="hero-actions"><Link to="/live" className="button primary">Watch the live demo <ArrowRight size={18}/></Link><Link to="/new" className="button secondary">Check AI access</Link></div><div className="hero-note"><ShieldCheck size={17}/> Safe demo · Fake data · Works without an AI model</div></div><div className="dashboard-preview"><div className="preview-top"><span><span className="small-dot green"/> SCOPELENS LIVE</span><span>CODE HELPER</span></div><div className="preview-flow"><div><span className="preview-icon neutral"><FolderOpen size={21}/></span><strong>My Project</strong><small>Allowed</small></div><div className="preview-line"/><div><span className="preview-icon agent"><Sparkles size={21}/></span><strong>AI</strong><small>Reads an issue</small></div><div className="preview-line danger"/><div><span className="preview-icon danger"><FileLock2 size={21}/></span><strong>Demo Password</strong><small>Blocked</small></div></div><div className="preview-alert"><ShieldOff size={18}/><div><strong>AI tried to open a file outside its job</strong><span>ScopeLens stopped it. The project task still works.</span></div><b>BLOCKED</b></div><div className="preview-bottom"><span>One job</span><span>One unexpected request</span><span>Protected</span></div></div></section>
    <section className="page product-split"><div className="product-card"><div className="product-icon">📁</div><div className="eyebrow">BEFORE YOU START</div><h2>What can AI access?</h2><p>Check permissions across tools. See risky combinations and try removing access to make the AI safer.</p><div className="product-tags"><span>Access</span><span>Risks</span><span>Try changes</span></div><Link to="/new" className="text-button">Analyze access →</Link></div><div className="product-card live"><div className="product-icon">🛡</div><div className="eyebrow">WHILE AI WORKS</div><h2>What is AI doing?</h2><p>Watch the same task with protection off and on. See dangerous requests get blocked while the real job continues.</p><div className="product-tags"><span>Actions</span><span>Alerts</span><span>Protection</span></div><Link to="/live" className="text-button">Open Live →</Link></div></section>
    <section className="page"><div className="demo-steps"><div><span>01</span><strong>I gave AI one job</strong><small>Fix my project.</small></div><div><span>02</span><strong>A file tried to redirect it</strong><small>Open a fake password outside the project.</small></div><div><span>03</span><strong>ScopeLens stopped it</strong><small>The AI still works on my project.</small></div></div></section>
  </>
}
