import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2, ShieldCheck, ShieldOff } from 'lucide-react'
import LiveGraph from '../components/LiveGraph'
import { api } from '../services/api'
import type { LiveComparison } from '../types'

export default function LiveCompare() {
  const [result, setResult] = useState<LiveComparison | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { api.liveCompare().then(setResult).catch(cause => setError(cause instanceof Error ? cause.message : 'Comparison failed')) }, [])
  return <section className="page live-compare-page"><div className="compare-intro"><div className="eyebrow">BEFORE & AFTER</div><h1>Same AI. Same job. <em>Different protection.</em></h1><p>Both sides check the same fake electricity bill and encounter the same injected instructions.</p></div>{error && <div className="error">{error}</div>}{result ? <><div className="live-compare-grid"><article className="comparison-card vulnerable"><div className="comparison-kicker"><ShieldOff size={20}/> PROTECTION OFF</div><h2>Sample accounts exposed</h2><p>The invoice steered AI to open the synthetic account database and send its contents to a local demo receiver.</p><LiveGraph graph={result.before.graph} compact/><div className="sample-account-result"><strong>Sample records reached the local receiver</strong><ul>{result.before.exposed_sample_accounts.map(record => <li key={record.account}>{record.customer} · {record.account} · ₹{record.balance_inr.toLocaleString('en-IN')}</li>)}</ul></div><div className="comparison-outcome danger"><strong>{result.before.summary.exposures} DEMO EXPOSURES</strong><span>Sample records only · nothing sent to the Internet</span></div></article><article className="comparison-card protected"><div className="comparison-kicker"><ShieldCheck size={20}/> PROTECTION ON</div><h2>Account lookup blocked</h2><p>ScopeLens denied the database read and send. The ₹1,250 bill check and payment preparation still completed.</p><LiveGraph graph={result.after.graph} compact/><div className="comparison-outcome safe"><strong>{result.after.summary.blocked} ACTIONS BLOCKED</strong><span>No sample account record was opened</span></div></article></div><div className="compare-outcome live-outcome"><CheckCircle2 size={24}/><div><strong>The bill task can continue without database access.</strong><p>Same task and same Demo AI replay on both sides. All records are synthetic.</p></div><Link to="/live?scenario=finance" className="button secondary">Try it live <ArrowRight size={16}/></Link></div></> : !error && <div className="panel loading-panel">Running the safe comparison…</div>}</section>
}
