import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, CheckCircle2, ShieldCheck, ShieldOff } from 'lucide-react'
import LiveGraph from '../components/LiveGraph'
import { api } from '../services/api'
import type { LiveComparison } from '../types'

export default function LiveCompare() {
  const [result, setResult] = useState<LiveComparison | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { api.liveCompare().then(setResult).catch(cause => setError(cause instanceof Error ? cause.message : 'Comparison failed')) }, [])
  return <section className="page live-compare-page"><div className="compare-intro"><div className="eyebrow">SCOPELENS LIVE · BEFORE / AFTER</div><h1>Same agent. Same prompt. <em>Different boundary.</em></h1><p>Both sides replay the same synthetic issue and tool requests. The only difference is the deterministic runtime guard.</p></div>{error && <div className="error">{error}</div>}{result ? <><div className="live-compare-grid"><article className="comparison-card vulnerable"><div className="comparison-kicker"><ShieldOff size={20}/> BEFORE · UNPROTECTED</div><h2>Simulated secret exposure</h2><p>The agent follows an instruction from untrusted issue text. Broad sandbox file access lets it read a fake secret and use a local demo sink.</p><div className="comparison-stats"><div><strong>{result.before.summary.exposures}</strong><span>Exposure events</span></div><div><strong>{result.before.local_sink_count}</strong><span>Local sink sends</span></div><div><strong>{result.before.summary.blocked}</strong><span>Blocked</span></div></div><LiveGraph graph={result.before.graph} compact/><div className="comparison-outcome danger"><strong>SIMULATED DATA EXPOSURE</strong><span>Fake data only · no Internet destination</span></div></article><article className="comparison-card protected"><div className="comparison-kicker"><ShieldCheck size={20}/> AFTER · SCOPELENS PROTECTED</div><h2>Critical action blocked</h2><p>The same request reaches the tool gateway. A secret outside the assigned project is blocked before the file is opened.</p><div className="comparison-stats"><div><strong>{result.after.summary.exposures}</strong><span>Exposure events</span></div><div><strong>{result.after.local_sink_count}</strong><span>Local sink sends</span></div><div><strong>{result.after.summary.blocked}</strong><span>Blocked</span></div></div><LiveGraph graph={result.after.graph} compact/><div className="comparison-outcome safe"><strong>CORE TASK STILL WORKING</strong><span>Repository access remains available</span></div></article></div><div className="compare-outcome live-outcome"><CheckCircle2 size={24}/><div><strong>The security boundary is code, outside the model.</strong><p>Same task: {result.same_task ? 'yes' : 'no'} · Same model: {result.same_model ? 'yes' : 'no'} · Local sandbox only.</p></div><Link to="/live" className="button secondary">Run it live <ArrowRight size={16}/></Link></div></> : !error && <div className="panel loading-panel">Building the before/after replay…</div>}</section>
}
